---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
library(rvest) 
PttMovie<-"https://www.ptt.cc/bbs/movie/index.html"
for(n in 1:6){
  PttContent <- read_html(PttMovie)
  pageup <- PttContent %>% html_nodes(".btn-group a") %>% html_attr("href")
  post_title <- PttContent %>% html_nodes(".title") %>% html_text()
  post_push <- PttContent %>% html_nodes(".nrec") %>% html_text()
  post_author <- PttContent %>% html_nodes(".author") %>% html_text()
  PttMovie_posts <- data.frame(Title = post_title,
                               PushNum = post_push,
                               Author = post_author)
  PttMovie <- paste("https://www.ptt.cc",pageup[4], sep="")
  nam <- paste("PttMovie_posts",n,sep="")
  assign(nam, PttMovie_posts)
}
PttMovie_posts_All <- rbind(PttMovie_posts1,PttMovie_posts2,PttMovie_posts3,PttMovie_posts4,PttMovie_posts5,PttMovie_posts6)



```

## 爬蟲結果呈現
```{r}
knitr::kable(PttMovie_posts_All[c("Title", "PushNum", "Author")]) 
```

## 解釋爬蟲結果 
```{r}
str(PttMovie_posts_All)
"爬出103個文章標題"
```

解釋解釋解釋解釋

```{r}
table(PttMovie_posts_All$Author)
"jay5566 5times"
```

解釋解釋解釋解釋
```{r}
"雖然不知道JAY5566是誰 但是他的文章推文數量都滿多的"
```